### ISSUE TITLE
Optical flow description

### ISSUE THREAD

**Issue by Zedliser** [kuznetckiy/pioneer-doc#11]
It might be a good idea to add information on altitude when using [Optical flow module](https://github.com/kuznetckiy/pioneer-doc/blob/master/module/optic.rst), e.g. that it is using tof module to get it while in tof's effective range and outside of it module uses barometer to get altitude and thus might be less accurate above ~1.5 meters as stated in [extension modules board](https://github.com/kuznetckiy/pioneer-doc/blob/master/module/board.rst).

**Comment by Zedliser** [comment]
Apart from that some secription on how to update module firmware as in [indoor navigation module](https://github.com/kuznetckiy/pioneer-doc/blob/master/module/indoor_nav.rst) would be really nice since it's not such an obvious task. Although above description lacks details on how to put module into bootloader mode, so it also needs an update. I will make a different issue for that matter.

**Comment by kuznetckiy** [comment]
внес, насчет перепрошивки еще добавлю
