### ISSUE TITLE
Firmware update indoor navigation module

### ISSUE THREAD

**Issue by Zedliser** [kuznetckiy/pioneer-doc#13]
[Current description](https://github.com/kuznetckiy/pioneer-doc/blob/master/module/indoor_nav.rst#%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B0-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8F-%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D0%B8) lacks details to make module enter bootload mode. It states that you have to connect battery to Pioneer but you actually have to connect battery while Start button is being pressed and check that all LEDs on the modules are lit. Only after that you can connect Pioneer to Pioneer Station and update firmware through it. Same goes for [indoor navigation beacon](https://github.com/kuznetckiy/pioneer-doc/blob/master/indoor_nav.rst#%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B8-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D0%B8). You hve to hold Menu button and press Power On/Off button to enter bootloader mode and then connect beacon to Pioneer station and launch Firmware update wizard.

**Comment by kuznetckiy** [comment]
внес
